### PR TITLE
Introduce Psalm, fix type issues and improve Travis config

### PR DESCRIPTION
**Pull request by tgalopin**

### CODE REVIEW

**Comment by tgalopin** [comment]
@paragonie-security Hey Scott!

I'm having many really useless false positives with Psalm and I'm considering to not add it as an automatic check. Even if it did give me a few good ideas, overall, the type system is way too strict to be useful IMHO (for instance it forces me to explicitly define all the key types of arrays, which is quite useless, it's either string or int: specifying it add complexity to the code for next to no advantage). Any opinion? Am I doing something wrong?

**Comment by paragonie-scott** [comment]
> Am I doing something wrong?

Yep. There are a couple types of checks that aren't usually helpful (they're prefixed with `Redundant`). Suppress those.

Otherwise:

> for instance it forces me to explicitly define all the key types of arrays, which is quite useless, it's either string or int: specifying it add complexity to the code for next to no advantage

Solving this *is* as simple as adding a declaration like this one:

```php
/** @var array<string, string> $trustedPart */
```

Modern IDEs (e.g. PHPStorm) will also use these declarations in their own static analysis engines (i.e. PHPStorm Inspections).

You don't need to add anything in terms of unnecessary executable code to make these errors vanish.

**Comment by paragonie-scott** [comment]
See #13 for an example that *should* work

**Comment by tgalopin** [comment]
Thanks for your super fast answer!

> Yep. There are a couple types of checks that aren't usually helpful (they're prefixed with `Redundant`). Suppress those.

Well, even so: the library being based on an array of configuration, I have tons of errors due to "mixed types" being used. Should I just disable these non-redundant rules? I already suppressed 6, that seem large to me :/ .

> Solving this *is* as simple as adding a declaration like this one:

It's not difficult but hugely time-consuming :/ ... I don't really want to do that now. I will merge the CS-fixer independently for now. If you have time/will to have a look at Psalm, don't hesitate, otherwise I feel it's a huge overhead not really worth it.

**Comment by tgalopin** [comment]
> See #13 for an example that *should* work

Unfortunately this syntax is not compatible with the Symfony Coding Standard :) .

**Comment by paragonie-scott** [comment]
Yikes. Yeah, I wouldn't worry too much about this right now.

**Pull request merged**
